### ISSUE TITLE
Are injections supposed to work?

### ISSUE THREAD

**Issue by p-groarke** [asutton/clang#32]
I get "error: expected injection" in examples and simple tests I've used. Are the injections supposed to be working? Other examples (like interfaces) are working fine.

```
$class the_future_is_now {
	constexpr {
		-> { int metaclasses_are_dope = 0; }
	}
};
// Hopefully the names of the constructs reflect how excited I am about the proposal. Pun intended.
```

**Comment by Dalzhim** [comment]
Looking at the [latest version of the proposal](https://herbsutter.files.wordpress.com/2017/07/p0707r1.pdf), it doesn't seem to have working examples for the injection syntax yet. Multiple examples in chapter three have links to compiling versions on cppx.godbolt.org, but those versions never use the arrow `->`. Here's also an explicit note from that paper :
>Note: This example (and quite a few others) will not compile in the prototype compiler yet for a number of incompleteness reasons, but here in particular because this code uses concepts and Clang does not yet have concepts.

So basically, the part of injections that seem to work right now are those :
```
$class mc
{
    mc() {/*do something*/}
    void f() {/*do something*/}
};
```

**Comment by p-groarke** [comment]
Thank you for the clarification. I went through the commits and it seems the currently supported syntax is the following:

```
-> do { int test; }
-> class C { /* ... */ }
```

These seem to be represented as lambdas underneath. With captures in the form of `-> [x] do { /* ... */ }`. So far my experiments with the injections that rely on class variables have failed.

You can find more examples in the tests that were written for the prototype (clang/test/CXX/meta/).
Good day

**Comment by p-groarke** [comment]
Thank you for the clarification. I went through the commits and it seems the currently supported syntax is the following:

```
-> do { int test; }
-> class C { /* ... */ }
```

These seem to be represented as lambdas underneath. With captures in the form of
`-> [x] do { /* ... */ }`
So far my experiments with the injections that rely on class variables have failed.

You can find more examples in the tests that were written for the prototype (clang/test/CXX/meta/).
Good day

edit: It seems I missed your edit :)

**Comment by Dalzhim** [comment]
There has been a rewrite that was published just yesterday and which changes a few things and improves the code injection mechanism. Here's some example code I just compiled successfully :
```
$class MyClass
{
    constexpr {
        for... (auto m : $prototype.member_variables())
            -> class { private: int idexpr(m.name()); public: int idexpr("get_", m.name())() const {
                    return idexpr(m.name());
                }
            };
    }
}

MyClass test
{
    int a, b, c;
};

constexpr {
    compiler.debug($test);
}

int main() {}
```
